// Second-pass ecosystem depth. These are concrete organizations and products;
// cluster labels organize discovery but never become selectable graph entities.
const C=(layer,id,name,type,products,names)=>({layer,id,name,type,products,names:names.split(',').map(value=>value.trim()).filter(Boolean)});

export const DEPTH_CLUSTERS=[
 C('materials','grid-utilities-global','Grid utilities for AI regions','Infrastructure cluster',['Grid capacity','Transmission','Power purchase'],'American Electric Power,Entergy,Exelon,PSEG,Xcel Energy,Ameren,FirstEnergy,Eversource Energy,National Grid plc,SSE plc,Iberdrola,Enel,RWE,E.ON,EDF,Engie,KEPCO,CLP Holdings,China Southern Power Grid,State Grid Corporation of China'),
 C('materials','nuclear-fuel-power','Nuclear power & fuel cycle','Infrastructure cluster',['Baseload electricity','Uranium','Small modular reactors'],'BWX Technologies,Centrus Energy,Orano,Framatome,Westinghouse Electric Company,Holtec International,NuScale Power,TerraPower,X-energy,Kairos Power,Rolls-Royce SMR,Ontario Power Generation,Bruce Power,Électricité de France,KHNP,Rosatom,CGN Power,CNNC,Energy Northwest,TVA'),
 C('materials','battery-backup-materials','Battery & backup-power inputs','Supply cluster',['UPS batteries','Copper','Cathode materials'],'CATL,BYD Energy Storage,LG Energy Solution,Samsung SDI,Panasonic Energy,Fluence,Northvolt,Saft,EnerSys,Eaton Energy Storage,Vertiv EnergyCore,Narada Power,EVE Energy,Hithium,Gotion High-Tech,Redwood Materials,Livent,Albemarle,SQM,Piedmont Lithium'),
 C('materials','thermal-materials','Thermal-interface & cooling materials','Supply cluster',['Thermal interface material','Dielectric coolant','Refrigerants'],'Henkel Electronics,Dow Performance Silicones,Shin-Etsu Thermal Interface Materials,Laird Performance Materials,Boyd Corporation,Indium Corporation,Wakefield Thermal,Fujipoly,Stockwell Elastomerics,DuPont Kalrez,Solvay Specialty Polymers,Chemours Opteon,Honeywell Solstice,Daikin Refrigerants,Fuchs Lubricants,Petro-Canada Lubricants,Engineered Fluids ElectroCool,Shell Immersion Cooling Fluid,Castrol ON Immersion Fluids,M&I Materials MIVOLT'),

 C('equipment','vacuum-abatement','Vacuum pumps & process abatement','Equipment cluster',['Vacuum systems','Gas abatement','Process exhaust'],'Edwards Vacuum,Ebara Precision Machinery,Pfeiffer Vacuum,Leybold,ULVAC,Busch Vacuum Solutions,Atlas Copco Vacuum,CS Clean Solutions,DAS Environmental Expert,Centrotherm Clean Solutions,Ecosys Abatement,Exyte Technology,KC Innovation,GST Global,Wonik QnC,Youngjin IND,Unisem Korea,Hugle Electronics,Taiyo Nippon Sanso Engineering,Air Water Mechatronics'),
 C('equipment','fab-automation','Fab automation & material handling','Equipment cluster',['AMHS','Wafer transport','Factory automation'],'Daifuku,Muratec,Tokyo Electron Device,Hirata Corporation,Sinfonia Technology,THK,SMC Corporation,Festo,IAI Corporation,Yaskawa Electric,Omron Automation,Keyence,Rockwell Automation,Siemens Digital Industries,Mitsubishi Electric Automation,Asyst Technologies,Brooks Automation,Rorze Corporation,Nidec Sankyo,Shinsung E&G'),
 C('equipment','mask-reticle','Photomask & reticle ecosystem','Manufacturing cluster',['Photomasks','Mask blanks','Reticle inspection'],'Toppan Photomask,Dai Nippon Printing Photomask,Photronics,Taiwan Mask Corporation,Compugraphics,Advanced Reproductions,SK-Electronics,Hoya Mask Blanks,AGC Electronics,Shin-Etsu Photomask Materials,Applied Materials PROVision,ZEISS AIMS,Lasertec Actis,KLA Teron,NuFlare EBM,IMS Multi-Beam Mask Writer,Mycronic Prexision,JEOL Electron Beam Lithography,Raith Nanofabrication,Heidelberg Instruments'),
 C('equipment','server-power-components','Server power electronics','Equipment cluster',['Power supplies','Busbars','Power conversion'],'Delta Electronics,Lite-On Technology,Chicony Power,Flex Power Modules,Advanced Energy Industries,Bel Power Solutions,TDK-Lambda,Artesyn Embedded Power,Murata Power Solutions,Infineon Power Systems,Monolithic Power Systems,Navitas Semiconductor,Power Integrations,Wolfspeed Power,ROHM Semiconductor,Vicor Corporation,AcBel Polytech,FSP Group,Mean Well,Schaffner'),
 C('equipment','optical-components-depth','Optical component supply chain','Equipment cluster',['Lasers','Transceivers','Connectors'],'Coherent Corp,Lumentum,II-VI Photonics,Fabrinet,Innolight Technology,Eoptolink Technology,Accelink Technologies,Source Photonics,AOI Applied Optoelectronics,Hisense Broadband,Sumitomo Electric Device Innovations,Mitsubishi Electric Optical Devices,Macom Photonics,Marvell Inphi,Broadcom Optical Systems,Senko Advanced Components,US Conec,Molex Optical Solutions,TE Connectivity Optical,Amphenol Fiber Systems'),

 C('fabrication','compound-semiconductor-fabs','Compound-semiconductor fabs','Manufacturing cluster',['Silicon photonics','GaN','SiC'],'GlobalFoundries Photonics,Lumentum Wafer Fab,Coherent Sherman,WIN Semiconductors,Visual Photonics Epitaxy,IQE,AXT Inc,Wolfspeed Mohawk Valley,onsemi East Fishkill,Infineon Kulim,STMicroelectronics Catania,Texas Instruments Lehi,Bosch Dresden,Rohm Apollo,San’an Integrated Circuit,HC SemiTek,Episil Technologies,United Monolithic Semiconductors,SMART Photonics,Advanced Micro Foundry'),
 C('fabrication','pcb-substrate-manufacturing','PCB & substrate manufacturing','Manufacturing cluster',['Server PCB','IC substrate','High-speed laminate'],'Zhen Ding Technology,Unimicron Technology,Compeq Manufacturing,Tripod Technology,Gold Circuit Electronics,Wus Printed Circuit,TTM Technologies,AT&S Chongqing,Ibiden Electronics,Shinko Electric Industries,Kinsus Interconnect,Daeduck Electronics,Simmtech,SEMCO Package Solutions,Shennan Circuits,Victory Giant Technology,Kinwong Electronic,Suntak Technology,Meiko Electronics,CMK Corporation'),
 C('fabrication','electronics-manufacturing','AI-system contract manufacturing','Manufacturing cluster',['Server assembly','Rack integration','Electronics manufacturing'],'Foxconn Industrial Internet,Quanta Computer,Wiwynn,Wistron,Inventec,Pegatron,Celestica,Jabil,Flex Ltd,Sanmina,USI Universal Scientific Industrial,Qisda,MiTAC Computing,Hyve Solutions,Ingrasys,ZT Systems Manufacturing,Compal Electronics,Kontron,Plexus Corp,Benchmark Electronics'),

 C('compute','ai-server-platforms','AI server platforms','Hardware cluster',['GPU servers','Rack-scale systems','Liquid-cooled systems'],'Gigabyte Giga Computing,ASUS Servers,ASRock Rack,MiTAC Computing Technology,QCT,Lenovo Neptune,Inspur NF Series,H3C UniServer,xFusion FusionServer,Fujitsu PRIMEHPC,NEC SX-Aurora,Atos Eviden BullSequana,Supermicro SuperCluster,Dell PowerEdge XE,HPE Cray XD,Cisco UCS AI,Oracle Exadata AI,IBM LinuxONE AI,Trenton Systems,One Stop Systems'),
 C('compute','chiplet-interconnect-products','Chiplet & die-to-die products','Technology cluster',['Die-to-die PHY','CXL','Chiplet fabric'],'UCIe Consortium,BoW Interface,Open Compute Project ODSA,Ayar Labs TeraPHY,Lightmatter Passage,Intel EMIB,Intel Foveros Direct,TSMC SoIC-X,TSMC LIPINCON,AMD Infinity Fabric,NVIDIA NVLink-C2C,Arm Chiplet System Architecture,Alphawave UCIe PHY,Synopsys UCIe IP,Cadence UCIe IP,Rambus UCIe Controller,Marvell CXL Switch,Astera Labs Scorpio,Microchip Switchtec,Credo HiWire'),
 C('compute','storage-controllers','AI storage controllers & media','Hardware cluster',['NVMe','SSD controllers','High-capacity drives'],'Samsung PM1743,Micron 9550 NVMe,Kioxia CM7,Solidigm D7,Western Digital Ultrastar,Seagate Exos,Phison Pascari,Silicon Motion MonTitan,Marvell Bravera,Microchip Flashtec,Broadcom MegaRAID,Memblaze PBlaze,ScaleFlux Computational Storage,Viking Enterprise Solutions,Nimbus Data,Pure Storage FlashBlade,VAST DataBox,DDN SFA,IBM FlashSystem,NetApp AFF'),
 C('compute','edge-module-vendors','Edge AI modules & boards','Hardware cluster',['Embedded accelerators','SOM','Industrial edge AI'],'Advantech Edge AI,AAEON AI,ADLINK Edge AI,Kontron AI,Vecow,Neousys Technology,Axiomtek,IEI Integration,DFI Inc,Avalue Technology,OnLogic,Connect Tech,Aetina,Seeed Studio reComputer,WINSYSTEMS,Premio Inc,Eurotech Edge AI,SECO Edge AI,Toradex,Variscite'),

 C('datacenter','electrical-switchgear','Data-center electrical infrastructure','Infrastructure cluster',['Switchgear','Transformers','Busway'],'ABB Electrification,Siemens Smart Infrastructure,Eaton Electrical,Schneider Electric Secure Power,GE Vernova Grid Solutions,Mitsubishi Electric Power Products,Hitachi Energy,Hammond Power Solutions,Virginia Transformer,Howard Industries,Prolec GE,Hyosung Heavy Industries,S&C Electric Company,Powell Industries,Vertiv ASCO,Rittal Power Distribution,Legrand Starline,Piller Power Systems,Socomec,Cummins Power Systems'),
 C('datacenter','generators-fuelcells','Backup generation & microgrids','Infrastructure cluster',['Generators','Fuel cells','Microgrids'],'Caterpillar Electric Power,Cummins Power Generation,Rolls-Royce mtu,Kohler Energy,Generac Industrial Power,Himoinsa,Rehlko,Doosan Fuel Cell,Bloom Energy,Ballard Power Systems,Plug Power,PowerSecure,Enchanted Rock,Aggreko,Energy Vault,Ameresco Microgrids,Scale Microgrids,Schneider Microgrid Solutions,Siemens Microgrid,GE Vernova Aeroderivative'),
 C('datacenter','cooling-equipment-depth','High-density cooling equipment','Infrastructure cluster',['CDU','Rear-door heat exchanger','Immersion tanks'],'LiquidCool Solutions,Green Revolution Cooling,Asperitas,Submer SmartPod,Iceotope Precision Liquid Cooling,ZutaCore HyperCool,CoolIT CHx,Vertiv Liebert XDU,Schneider Motivair CDU,Johnson Controls Silent-Aire,Modine Airedale,Stulz CyberCool,Munters SyCool,Daikin Applied,Carrier AquaEdge,Trane CenTraVac,Boyd Liquid Cooling,JetCool SmartPlate,Chilldyne Negative Pressure,Accelsius NeuCool'),
 C('datacenter','dc-developers-asia','Asia-Pacific data-center operators','Infrastructure cluster',['Colocation','Hyperscale campuses','Interconnection'],'AirTrunk,NextDC,Macquarie Data Centres,Digital Edge,Princeton Digital Group,ST Telemedia Global Data Centres,Keppel Data Centres,NTT Global Data Centers Japan,KDDI Telehouse,Colt Data Centre Services,Bridge Data Centres,Chayora,SpaceDC,DayOne Data Centers,CtrlS Datacenters,Sify Data Centers,Yotta Infrastructure,Nxtra by Airtel,AdaniConneX,BDx Data Centers'),
 C('datacenter','dc-developers-europe','European data-center operators','Infrastructure cluster',['Colocation','Hyperscale campuses','Sovereign hosting'],'OVHcloud Data Centers,Data4,atNorth,Green Mountain Data Centres,Bulk Infrastructure,AtlasEdge,Global Switch,Telehouse Europe,Interxion,DigiPlex,NorthC Datacenters,nLighten,Ark Data Centres,Vantage Data Centers EMEA,STACK Infrastructure EMEA,Iron Mountain EMEA,Maincubes,CloudHQ Europe,Penta Infra,Serverfarm'),
 C('datacenter','dc-construction-specialists','Data-center engineering & construction','Infrastructure cluster',['EPC','Mechanical systems','Commissioning'],'Mercury Engineering,Winthrop Technologies,Keeley Construction,Clune Construction,Fortis Construction,Whiting-Turner,Skanska Mission Critical,Suffolk Technologies,JE Dunn Construction,Hoffman Construction,Cupertino Electric,Rosendin Electric,Southland Industries,Faith Technologies,McKinstry,EMCOR Group,Comfort Systems USA,Salute Mission Critical,Linesight,Arcadis Data Centers'),

 C('cloud','regional-cloud-europe','European sovereign & regional clouds','Cloud cluster',['Compute','Managed Kubernetes','Sovereignty'],'Hetzner Cloud,Scaleway,IONOS Cloud,Exoscale,UpCloud,Leaseweb Cloud,Open Telekom Cloud,Aruba Cloud,OVHcloud Public Cloud,Clever Cloud,Gridscale,Elastx,City Network Cleura,Brightbox,CloudSigma,STACKIT,Orange Business Cloud,Swisscom Cloud,T-Systems Cloud,Outscale'),
 C('cloud','regional-cloud-asia','Asian regional clouds','Cloud cluster',['Compute','AI APIs','Sovereign regions'],'Naver Cloud,KT Cloud,NHN Cloud,Kakao Cloud,Sakura Cloud,IIJ GIO,Fujitsu Uvance Cloud,NEC Cloud,NTT Communications Cloud,Oracle Alloy Japan,Rakuten Cloud,Telstra Cloud,Optus Cloud,Singtel Paragon,Telkomsigma,Indosat AI Cloud,Viettel Cloud,FPT Cloud,Tata Communications Cloud,JioCloud'),
 C('cloud','gpu-marketplaces','GPU capacity marketplaces','Cloud cluster',['On-demand GPU','Bare metal accelerators','Distributed compute'],'Vast.ai,TensorDock,SaladCloud,io.net,Akash Network,Gensyn,Hyperbolic,Prime Intellect Compute,Shadeform,JarvisLabs.ai,Genesis Cloud,DataCrunch,Oblivus,Thunder Compute,Massed Compute,Hyperstack,Ori Industries,NexGen Cloud,Crusoe Cloud Marketplace,WhiteFiber'),

 C('models','regional-model-labs-asia','Asian foundation-model labs','Research cluster',['Language models','Multimodal models','Regional languages'],'Sakana AI,Preferred Networks AI,NTT Human Informatics Laboratories,Rakuten Institute of Technology,Naver HyperCLOVA X,Kakao Brain,LG AI Research,Samsung Research AI Center,SK Telecom A.X,Upstage AI,NC AI,Korea Institute of Science and Technology Information AI,NII Japan LLM Center,ELYZA,Rinna Co.,Stockmark,ABEJA,AI Singapore SEA-LION,Tech Mahindra Makers Lab,Sarvam AI'),
 C('models','regional-model-labs-europe','European foundation-model labs','Research cluster',['Language models','Sovereign AI','Multimodal models'],'LightOn,Aleph Alpha Research,Black Forest Labs Research,Kyutai,Cradle AI,Poolside Research,Magic LTM,DeepL Research,Silo AI Research,Poro AI,TurkuNLP,ELLIS Institute Tübingen,LAION,OpenGPT-X,Occiglot,Barcelona Supercomputing Center AI,ELLIS Alicante,Swiss AI Initiative,CERN OpenLab AI,Tilde AI'),
 C('models','enterprise-model-builders','Enterprise model builders','Research cluster',['Domain models','Private deployment','Industry AI'],'Writer AI,Typeface,AI21 Labs Research,Contextual AI,Rhymes AI,Imbue,Goodfire AI,Reka AI Research,Essential AI Research,Arcee AI Models,Databricks Mosaic AI Research,Snowflake Arctic Team,ServiceNow Research,Salesforce AI Research,SAP AI Research,Oracle Labs AI,IBM Research Granite,Intel Labs AI,Qualcomm AI Research,Bosch Center for AI'),
 C('models','science-model-labs','Scientific foundation-model organizations','Research cluster',['Biology','Chemistry','Materials science'],'Isomorphic Labs,Generate Biomedicines Research,Recursion Valence Labs,Insilico Medicine AI,Schrödinger Machine Learning,Relay Therapeutics AI,Exscientia AI,BenevolentAI Research,Owkin Research,Tempus Research,Formation Bio,Latent Labs,Chai Discovery,FutureHouse Research,Periodic Labs Research,Orbital Materials Research,Microsoft Research AI4Science,Google DeepMind Science,Meta FAIR Science,NVIDIA BioNeMo Research'),
 C('models','china-model-labs-depth','Chinese model organizations','Research cluster',['Foundation models','Multimodal AI','Industry models'],'InclusionAI,Ant Ling Team,Meituan LongCat Team,RedNote HiLab,JD Explore Academy,JD JoyAI,OPPO AndesAI,vivo AI Lab,Honor MagicLM,Lenovo AI Lab,NetEase Fuxi,NetEase Youdao AI,NetEase Leihuo AI,Kunlun Tech Skywork,360 AI Research,SenseTime Research,Chinese Academy of Sciences Automation Institute,Beijing Academy of Artificial Intelligence,IDEA Research,Tsinghua KEG Lab'),

 C('infra','model-evaluation-depth','Model evaluation & observability','Platform cluster',['Evals','Tracing','Production monitoring'],'LangSmith,Langfuse,Phoenix by Arize,Weights & Biases Weave,OpenAI Evals,Inspect AI,DeepEval,Ragas,Giskard AI,Confident AI,Evidently AI,Kolena,Traceloop,AgentOps,LangWatch,Parea AI,Lunary,Maxim AI,Literal AI,Comet Opik'),
 C('infra','ai-security-depth','AI security & red teaming','Platform cluster',['Model security','Prompt defense','Red teaming'],'Lakera,Protect AI,HiddenLayer,Robust Intelligence,Cisco AI Defense,CalypsoAI,Prompt Security,Zenity Security,Noma Security,Invariant Labs,Adversa AI,Haize Labs,Gray Swan AI,AIM Security,LayerX Security,Reality Defender,Harmonic Security,Pillar Security,DeepKeep,Enkrypt AI'),
 C('infra','synthetic-data-depth','Synthetic data & simulation','Platform cluster',['Synthetic datasets','Privacy','Scenario generation'],'MOSTLY AI,Gretel Synthetic Data,Tonic.ai,Hazy,Synthesized,Statice,YData,Gencove,Rendered.ai,Parallel Domain,Applied Intuition Simulation,Cognata,AImotive aiSim,Scale Donovan Simulation,Synthesis AI Human Data,Datagen,Neurolabs,Anyverse,Foretellix,Helm.ai World Models'),
 C('infra','data-licensing','Data licensing & rights infrastructure','Platform cluster',['Licensed corpora','Media rights','Attribution'],'Defined.ai Data Marketplace,Shutterstock AI Data,Getty Images Generative AI,Adobe Stock Data,DataCite,Copyright Clearance Center,TollBit,Human Native AI,Calliope Networks,Spawning AI,Avail Data Licensing,Dow Jones Factiva AI,LexisNexis AI Data,Thomson Reuters Data,Reddit Data API,Stack Overflow API,Common Crawl Foundation,Wikimedia Enterprise,Internet Archive Research Services,News Corp AI Licensing'),

 C('developer','agent-frameworks-depth','Agent frameworks & orchestration','Software cluster',['Agent graphs','Tool execution','Memory'],'Mastra,VoltAgent,Agno,OpenAI Swarm,Microsoft AutoGen,Google Agent Development Kit,CrewAI Enterprise,LangGraph Platform,LlamaIndex Workflows,PydanticAI,Smolagents,Semantic Router,Haystack Agents,Camel AI,AutoGPT Platform,BabyAGI,Letta,MemGPT,SuperAGI,OpenHands'),
 C('developer','inference-compilers-depth','Inference compilers & kernels','Software cluster',['Kernel generation','Graph compilation','Quantization'],'OpenAI Triton Compiler,MLC LLM,Apache TVM,IREE,OpenXLA,TensorRT,TensorRT-LLM,ONNX Runtime,Intel OpenVINO,AMD MIGraphX,ROCm Composable Kernel,ThunderKittens,FlashInfer,FlashAttention,TileLang,Mojo Compiler,Modular MAX,BitBLAS,AutoAWQ,AutoGPTQ'),
 C('developer','local-ai-stack','Local and edge model runtimes','Software cluster',['Local inference','Quantization','Desktop serving'],'Ollama,LM Studio,Jan,LocalAI,GPT4All,KoboldCpp,Text Generation WebUI,Msty,PocketPal AI,MLC Chat,WebLLM,ExecuTorch,MediaPipe LLM Inference,ONNX Runtime GenAI,OpenVINO GenAI,LlamaEdge,Wasmtime AI,WasmEdge AI,Apple MLX LM,Qualcomm AI Hub'),

 C('agents','enterprise-agent-platforms','Enterprise agent platforms','Agent cluster',['Workflow automation','Governance','Connectors'],'Microsoft Copilot Studio,Google Agentspace,Amazon Bedrock Agents,Salesforce Agentforce,ServiceNow AI Agent Orchestrator,SAP Joule Agents,Oracle AI Agent Studio,IBM watsonx Orchestrate,UiPath Agent Builder,Automation Anywhere AI Agent Studio,Workato Agentic,Tray.ai Merlin Agents,Boomi Agentstudio,MuleSoft Agent Fabric,Pegasystems Agentic Process Fabric,Appian AI Agents,Creatio AI Agents,OutSystems Agent Workbench,Retool Agents,DataRobot Agent Workforce'),
 C('agents','research-browser-agents','Research & browser agents','Agent cluster',['Web research','Browser control','Knowledge synthesis'],'OpenAI Deep Research,Google Deep Research,Perplexity Deep Research,Claude Research,Genspark Super Agent,Manus AI,Fellou,Convergence Proxy,MultiOn,HyperWrite Agent,Harpa AI,Browserbase Stagehand,Skyvern,Steel Browser,Firecrawl Agent,Exa Websets,Parallel Web Systems,Tavily Research,You.com Research,Phind Research'),
 C('agents','operations-agents','IT & operations agents','Agent cluster',['Incident response','Cloud operations','Security operations'],'PagerDuty Advance,Datadog Bits AI,Splunk AI Assistant,Dynatrace Davis AI,New Relic AI,Elastic AI Assistant,Sentry Seer,Rootly AI,incident.io AI,Shoreline Op,BigPanda AI,ServiceNow ITOM AI,IBM Concert,Cisco AI Assistant for Security,CrowdStrike Charlotte AI,Microsoft Security Copilot,Palo Alto Cortex Copilot,Sophos AI Assistant,Wiz AI,Orca AI Assistant'),

 C('applications','healthcare-ai-depth','Healthcare AI products','Application cluster',['Clinical documentation','Diagnostics','Care operations'],'Abridge,Ambience Healthcare,Nabla,Corti,Suki,Notable Health,Qventus,Regard,Glass Health,OpenEvidence,Hippocratic AI,Infinitus Systems,AKASA,Clarify Health,PathAI,Paige AI,Proscia,Aidoc,Viz.ai,HeartFlow,Butterfly Network,Caption Health,Rad AI,Subtle Medical,Owkin K Navigator'),
 C('applications','legal-finance-depth','Legal & financial AI products','Application cluster',['Legal work','Banking','Investment research'],'Hebbia Matrix,Luminance,Robin AI,Spellbook,EvenUp,Clio Duo,Thomson Reuters CoCounsel,Lexis+ AI,vLex Vincent AI,Paxton AI,Blue J,Norm AI,Greenlite AI,WorkFusion AI,Ocrolus,AlphaSense Generative Search,FinChat,Boosted.ai,Canoe Intelligence,RavenPack AI,Feedzai,Riskified,Featurespace,Quantexa,ComplyAdvantage'),
 C('applications','industrial-ai-depth','Industrial AI products','Application cluster',['Predictive maintenance','Digital twins','Quality inspection'],'Siemens Industrial Copilot,Schneider EcoStruxure AI,ABB Ability Genix,Rockwell FactoryTalk Analytics,Honeywell Forge AI,GE Vernova Digital,AVEVA Industrial AI,Emerson AspenTech AI,PTC ServiceMax AI,Hexagon Nexus AI,Autodesk Construction IQ,Procore Copilot,Samsara Intelligence,Motive AI Fleet,Augury,Infinite Uptime,Sight Machine,Litmus Automation,Falkonry,Cognite Atlas AI,Uptake Industrial AI,Instrumental AI,Landing AI,Elementary AI,Robovision'),
 C('applications','commerce-marketing-depth','Commerce & marketing AI','Application cluster',['Personalization','Merchandising','Campaign generation'],'Klaviyo AI,HubSpot Breeze,Adobe Journey Optimizer AI,BrazeAI,Iterable AI,Attentive AI,Yotpo AI,Nosto,Lily AI,Bloomreach Loomi,Algolia Recommend,Coveo Commerce AI,Dynamic Yield,Constructor.io,Bluecore,Persado,Jasper Marketing AI,Copy.ai GTM AI,Typeface Arc,Writer AI Studio,Mutiny AI,Unbounce Smart Copy,Omneky,Pencil AI,Creatopy AI'),
 C('applications','education-public-depth','Education & public-service AI','Application cluster',['Tutoring','Assessment','Citizen services'],'Khanmigo,Duolingo Max,Quizlet Q-Chat,CheggMate,Photomath AI,Socratic by Google,Carnegie Learning MATHia,Century Tech,Squirrel AI,Riiid,MagicSchool AI,SchoolAI,Curipod,Brisk Teaching,TeachMateAI,Gradescope AI,Turnitin AI Writing,Ellucian AI,Mainstay Education,Element451 Bolt,Polis AI,Granicus AI,Tyler Technologies AI,Palantir FedStart AI,OpenGov AI'),

 C('robotics','warehouse-logistics-depth','Warehouse & logistics robotics','Robotics cluster',['Autonomous mobile robots','Picking','Sortation'],'Locus Robotics,Symbotic,Exotec,Geek+ Robotics,Hai Robotics,Quicktron,ForwardX Robotics,Addverb,Seegrid,OTTO Motors,MiR,Fetch Robotics,Zebra Fetch,Vecna Robotics,Agilox,AutoStore,Ocado Technology,RightHand Robotics,Covariant Robotics,Nomagic,Ambi Robotics,Plus One Robotics,Mujin,XYZ Robotics,Berkshire Grey'),
 C('robotics','agriculture-mining-depth','Agriculture & mining autonomy','Robotics cluster',['Autonomous equipment','Field robotics','Inspection'],'John Deere Blue River,CNH Raven,AGCO Precision Planting,Trimble Agriculture,Carbon Robotics,Monarch Tractor,Naïo Technologies,FarmWise,Burro Robotics,Agtonomy,SwarmFarm Robotics,Advanced Farm Technologies,Iron Ox,Bonsai Robotics,Caterpillar MineStar,Komatsu FrontRunner,Hexagon Autonomous Mining,SafeAI,ASI Mining,Pronto.ai,Exyn Technologies,Emesent,Flyability,Percepto Robotics,ANYbotics Inspection'),
 C('robotics','medical-service-depth','Medical & service robotics','Robotics cluster',['Surgical robots','Care robots','Commercial service robots'],'Intuitive Surgical,Medtronic Hugo,Johnson & Johnson Ottava,CMR Surgical,Distalmotion,MicroPort MedBot,SS Innovations,PROCEPT BioRobotics,Stereotaxis,Globus Medical Robotics,Smith+Nephew CORI,Zimmer Biomet ROSA,Diligent Robotics,Moxi Robot,Aethon TUG,Relay Robotics,Pudu Robotics,Keenon Robotics,Bear Robotics,Richtech Robotics,SoftBank Robotics,Temi Robotics,Blue Frog Robotics,temi Global,Hello Robot'),
 C('robotics','autonomous-vehicles-depth','Autonomous trucking & mobility','Robotics cluster',['Robotaxi','Autonomous trucking','Delivery robots'],'Aurora Innovation,Kodiak Robotics,Gatik,Waabi,Plus Automation,Torc Robotics,Einride,Outrider,Embark Trucks Platform,May Mobility,Zoox,Nuro,Serve Robotics,Starship Technologies,Coco Robotics,Kiwibot,Cartken,Avride,Mobileye Drive,Wayve,Oxbotica Oxa,Applied EV,Autonomous A2Z,Motional,WeRide Robobus')
];
