import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { LAYERS } from './data.js';
import { entityKind } from './entity-kind.js';

const DEPENDENCY_SOURCE=new Set(['RUNS_ON','TRAINS_ON','DEPENDS_ON','USES_MODEL_FROM']);
const MUTUAL=new Set(['PARTNERS_WITH','INTEGRATES_WITH','COMPETES_WITH']);
const directionalNeighbor=(relationship,current,direction)=>{if(MUTUAL.has(relationship.type))return relationship.source===current?relationship.target:relationship.target===current?relationship.source:null;const [consumer,provider]=DEPENDENCY_SOURCE.has(relationship.type)?[relationship.source,relationship.target]:[relationship.target,relationship.source];return direction==='upstream'?(consumer===current?provider:null):(provider===current?consumer:null)};

export class EcosystemScene {
 constructor(mount,entities,relationships,onSelect){
  this.mount=mount;this.entities=entities;this.relationships=relationships;this.onSelect=onSelect;this.nodes=new Map();this.labelEls=new Map();this.activeLabelIds=new Set();this.lines=[];this.visibleLayers=new Set(LAYERS.map(l=>l.id));this.activeGeography='all';this.relationFilter='ALL';this.timeYear=2026;this.view='ecosystem';this.reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
  this.scene=new THREE.Scene();this.scene.fog=new THREE.FogExp2(0x090b0c,.0047);
  this.camera=new THREE.PerspectiveCamera(42,innerWidth/innerHeight,.1,1200);this.camera.position.set(112,58,135);
  this.renderer=new THREE.WebGLRenderer({antialias:true,alpha:true,powerPreference:'high-performance'});this.renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));this.renderer.setSize(innerWidth,innerHeight);this.renderer.outputColorSpace=THREE.SRGBColorSpace;this.renderer.toneMappingExposure=1.22;mount.append(this.renderer.domElement);
  this.controls=new OrbitControls(this.camera,this.renderer.domElement);Object.assign(this.controls,{enableDamping:true,dampingFactor:.065,minDistance:24,maxDistance:280,enablePan:true,screenSpacePanning:true,zoomToCursor:true,rotateSpeed:.48,zoomSpeed:.82,panSpeed:.72,autoRotate:!this.reduced,autoRotateSpeed:.1});this.controls.target.set(10,5,0);
  this.scene.add(new THREE.HemisphereLight(0xf0f5f1,0x20252a,2.05));this.scene.add(new THREE.AmbientLight(0xb8c5c2,.42));const light=new THREE.PointLight(0xe0b678,135,250);light.position.set(10,80,35);this.scene.add(light);
  this.universe=new THREE.Group();this.scene.add(this.universe);this.buildArchitecture();this.buildNodes();this.buildGravityRanking();this.buildModelRanking();this.bind();this.animate();
 }
 buildArchitecture(){
  this.layerGroups=new Map();this.architectureGuides=[];
  LAYERS.forEach((layer,idx)=>{const g=new THREE.Group();g.userData.layer=layer.id;this.universe.add(g);this.layerGroups.set(layer.id,g);
   const ring=new THREE.Mesh(new THREE.TorusGeometry(25+idx*3.1,.035,3,96),new THREE.MeshBasicMaterial({color:layer.color,transparent:true,opacity:.13,depthWrite:false}));ring.rotation.x=Math.PI/2;ring.position.set(10,layer.y,0);g.add(ring);this.architectureGuides.push(ring);
   const plane=new THREE.Mesh(new THREE.RingGeometry(24+idx*3.1,24.12+idx*3.1,96),new THREE.MeshBasicMaterial({color:layer.color,transparent:true,opacity:.035,side:THREE.DoubleSide,depthWrite:false}));plane.rotation.x=Math.PI/2;plane.position.set(10,layer.y,0);g.add(plane);this.architectureGuides.push(plane);
  });
  const grid=new THREE.GridHelper(280,40,0x434849,0x202426);grid.position.y=-61;grid.material.transparent=true;grid.material.opacity=.28;this.universe.add(grid);this.architectureGuides.push(grid);
  const axisMat=new THREE.LineBasicMaterial({color:0xffffff,transparent:true,opacity:.12}),pts=[new THREE.Vector3(10,-60,0),new THREE.Vector3(10,72,0)],axis=new THREE.Line(new THREE.BufferGeometry().setFromPoints(pts),axisMat);this.universe.add(axis);this.architectureGuides.push(axis);
 }
 buildNodes(){
  const shared={organization:new THREE.SphereGeometry(1,12,8),hardware:new THREE.BoxGeometry(1.45,1.45,1.45),software:new THREE.OctahedronGeometry(1.15,0)};
  const membersByLayer=new Map(LAYERS.map(l=>[l.id,this.entities.filter(e=>e.layer===l.id)]));
  this.entities.forEach(e=>{const layer=LAYERS.find(l=>l.id===e.layer),arr=membersByLayer.get(e.layer),idx=e.positionIndex,clusters=[...new Set(arr.map(x=>x.cluster))],clusterIndex=clusters.indexOf(e.cluster),clusterMembers=arr.filter(x=>x.cluster===e.cluster),within=clusterMembers.indexOf(e),sector=Math.PI*2/clusters.length,angle=clusterIndex*sector+(within-(clusterMembers.length-1)/2)*Math.min(.13,sector/Math.max(2,clusterMembers.length))+(LAYERS.indexOf(layer)*.71),radius=24+LAYERS.indexOf(layer)*3.05+(within%5)*2.15;
   const importance=.58+e.importanceLevel*.28,kind=entityKind(e),geo=shared[kind],finish=kind==='organization'?{roughness:.78,metalness:.05,emissiveIntensity:.045,opacity:.94}:kind==='hardware'?{roughness:.28,metalness:.76,emissiveIntensity:.07,opacity:.96}:{roughness:.42,metalness:.12,emissiveIntensity:.22,opacity:.84};
   const mat=new THREE.MeshStandardMaterial({color:layer.color,emissive:layer.color,transparent:true,...finish});const mesh=new THREE.Mesh(geo,mat);if(kind==='software')mesh.rotation.y=Math.PI/4;
   mesh.position.set(10+Math.cos(angle)*radius,layer.y+((within%4)-1.5)*1.05,Math.sin(angle)*radius);mesh.userData={entity:e,kind,baseScale:importance,baseEmissive:finish.emissiveIntensity,baseOpacity:finish.opacity};mesh.scale.setScalar(this.reduced?importance:.01);this.layerGroups.get(e.layer).add(mesh);this.nodes.set(e.id,mesh);
   if(!this.reduced)setTimeout(()=>{mesh.scale.setScalar(importance)},80+LAYERS.indexOf(layer)*40+(idx%40)*8);
   if(e.importanceLevel===3||(e.type==='Model'&&e.importanceLevel>=2)){const el=document.createElement('span');el.className='node-label';el.textContent=e.name;el.dataset.id=e.id;this.mount.append(el);this.labelEls.set(e.id,el);}
  });
 }
 buildGravityRanking(){const degree=new Map(this.entities.map(entity=>[entity.id,0])),weights={confirmed:1,reported:.65,inferred:.25,representative:.05};this.relationships.forEach(r=>{const weight=weights[r.status]??.5;if(degree.has(r.source))degree.set(r.source,degree.get(r.source)+weight);if(degree.has(r.target))degree.set(r.target,degree.get(r.target)+weight)});this.gravityScore=new Map(this.entities.map(entity=>[entity.id,entity.importanceLevel*20+Math.sqrt(degree.get(entity.id)||0)*8]));this.gravityEntities=[...this.entities].sort((a,b)=>this.gravityScore.get(b.id)-this.gravityScore.get(a.id)||a.name.localeCompare(b.name));this.gravityIndex=new Map(this.gravityEntities.map((entity,index)=>[entity.id,index]));this.gravityEntities.slice(0,45).forEach(entity=>{if(this.labelEls.has(entity.id))return;const el=document.createElement('span');el.className='node-label gravity-label';el.textContent=entity.name;el.dataset.id=entity.id;el.dataset.gravityOnly='true';this.mount.append(el);this.labelEls.set(entity.id,el)})}
 buildModelRanking(){const modelsById=new Map(this.entities.filter(entity=>entity.type==='Model').map(entity=>[entity.id,entity])),portfolios=new Map();this.relationships.filter(r=>r.type==='DEVELOPS'&&modelsById.has(r.target)).forEach(r=>{if(!portfolios.has(r.source))portfolios.set(r.source,[]);const portfolio=portfolios.get(r.source);if(!portfolio.includes(r.target))portfolio.push(r.target)});this.modelPortfolioByModel=new Map();this.modelEntities=[];portfolios.forEach((ids,producer)=>{const items=ids.map(id=>modelsById.get(id)).filter(Boolean);if(!items.length)return;const portfolio={producer,root:items[0].id,items};items.forEach(model=>this.modelPortfolioByModel.set(model.id,portfolio));this.modelEntities.push(items[0])});this.modelEntities.sort((a,b)=>b.importanceLevel-a.importanceLevel||a.name.localeCompare(b.name));this.modelOrder=new Map(this.modelEntities.map((entity,index)=>[entity.id,index]));this.modelEntities.forEach(entity=>this.ensureLabel(entity.id,'model-label','modelOnly'))}
 ensureLabel(id,className='',flag=null){if(this.labelEls.has(id)){const el=this.labelEls.get(id);if(className)el.classList.add(className);if(flag)el.dataset[flag]='true';return el}const entity=this.nodes.get(id)?.userData.entity;if(!entity)return null;const el=document.createElement('span');el.className=`node-label ${className}`.trim();el.textContent=entity.name;el.dataset.id=id;if(flag)el.dataset[flag]='true';this.mount.append(el);this.labelEls.set(id,el);return el}
 setActiveLabels(ids=[]){this.activeLabelIds=new Set(ids);this.labelEls.forEach((el,id)=>el.classList.toggle('active-node-label',this.activeLabelIds.has(id)));this.activeLabelIds.forEach(id=>this.ensureLabel(id,'active-node-label'))}
 bind(){this.raycaster=new THREE.Raycaster();this.pointer=new THREE.Vector2();let down={x:0,y:0};
  this.renderer.domElement.addEventListener('pointerdown',e=>down={x:e.clientX,y:e.clientY});this.renderer.domElement.addEventListener('pointerup',e=>{if(Math.hypot(e.clientX-down.x,e.clientY-down.y)>5)return;this.pick(e)});
  this.renderer.domElement.addEventListener('pointermove',e=>{this.pointer.set(e.clientX/innerWidth*2-1,-e.clientY/innerHeight*2+1);this.raycaster.setFromCamera(this.pointer,this.camera);const hit=this.raycaster.intersectObjects([...this.nodes.values()],false)[0];this.renderer.domElement.style.cursor=hit?'pointer':'grab'});
  addEventListener('resize',()=>{this.camera.aspect=innerWidth/innerHeight;this.camera.updateProjectionMatrix();this.renderer.setSize(innerWidth,innerHeight)});
 }
 pick(e){this.pointer.set(e.clientX/innerWidth*2-1,-e.clientY/innerHeight*2+1);this.raycaster.setFromCamera(this.pointer,this.camera);const hit=this.raycaster.intersectObjects([...this.nodes.values()].filter(n=>n.visible),false)[0];if(hit)this.onSelect(hit.object.userData.entity.id)}
 animate(){requestAnimationFrame(()=>this.animate());this.controls.update();this.updateCamera();this.updateNodePositions();this.updateLabels();this.renderer.render(this.scene,this.camera)}
 updateCamera(){if(!this.tween)return;const t=Math.min(1,(performance.now()-this.tween.start)/this.tween.duration),ease=1-Math.pow(1-t,3);this.camera.position.lerpVectors(this.tween.from,this.tween.to,ease);this.controls.target.lerpVectors(this.tween.targetFrom,this.tween.targetTo,ease);if(t===1)this.tween=null}
 updateNodePositions(){const now=performance.now();this.nodes.forEach(node=>{const move=node.userData.move;if(!move)return;const t=Math.min(1,(now-move.start)/move.duration),ease=1-Math.pow(1-t,3);node.position.lerpVectors(move.from,move.to,ease);if(t===1)node.userData.move=null})}
 updateLabels(){const projected=[],v=new THREE.Vector3();this.labelEls.forEach((el,id)=>{const n=this.nodes.get(id),active=this.activeLabelIds.has(id);if((el.dataset.gravityOnly&&this.view!=='gravity'&&!active)||(el.dataset.modelOnly&&this.view!=='models'&&n?.userData.entity.importanceLevel<2&&!active)||!n?.visible||!n.parent?.visible){el.hidden=true;return}const world=n.getWorldPosition(new THREE.Vector3());v.copy(world).project(this.camera);const visible=v.z<1&&Math.abs(v.x)<1.05&&Math.abs(v.y)<1.05&&this.camera.position.distanceTo(world)<185;if(!visible){el.hidden=true;return}projected.push({el,n,active,x:(v.x*.5+.5)*innerWidth+10,y:(-v.y*.5+.5)*innerHeight-4,importance:n.userData.entity.importanceLevel})});projected.sort((a,b)=>Number(b.active)-Number(a.active)||b.importance-a.importance||b.n.material.opacity-a.n.material.opacity);const occupied=[];projected.forEach(item=>{const width=Math.max(38,item.el.textContent.length*5.2),offsets=item.active?[0,-16,16,-32,32]:[0];let placement=null;for(const dy of offsets){const box={left:item.x-3,right:item.x+width,top:item.y+dy-7,bottom:item.y+dy+7};if(!occupied.some(other=>!(box.right<other.left||box.left>other.right||box.bottom<other.top||box.top>other.bottom))){placement={box,dy};break}}if(!placement&&item.active)placement={box:{left:item.x-3,right:item.x+width,top:item.y-7,bottom:item.y+7},dy:0};item.el.hidden=!placement;if(placement){occupied.push(placement.box);item.el.style.transform=`translate(${item.x}px,${item.y+placement.dy}px)`;item.el.style.opacity=item.active?'1':item.n.material.opacity<.5?'.28':'.94'}})}
 focus(id,distance=30){const n=this.nodes.get(id);if(!n)return;this.controls.autoRotate=false;const target=n.getWorldPosition(new THREE.Vector3()),dir=this.camera.position.clone().sub(this.controls.target).normalize();this.tween={start:performance.now(),duration:this.reduced?1:900,from:this.camera.position.clone(),to:target.clone().add(dir.multiplyScalar(distance)),targetFrom:this.controls.target.clone(),targetTo:target}}
 clearLines(){this.lines.forEach(object=>{this.scene.remove(object);object.traverse(child=>{child.geometry?.dispose();child.material?.dispose()})});this.lines=[]}
 relationshipVisible(relationship){return (!relationship.activeFrom||relationship.activeFrom<=this.timeYear)&&(!relationship.activeTo||relationship.activeTo>=this.timeYear)}
 relationshipWeight(relationship){const confidence={confirmed:1,reported:.68,inferred:.38,representative:.23}[relationship.status]??.5,dated=relationship.activeFrom||relationship.activeTo;return confidence*(dated?1:.72)}
 makeLine(a,b,relationship,highlight=false,opacity=null,colorOverride=null){const rel=typeof relationship==='string'?{type:relationship,status:'representative'}:relationship,type=rel.type;if(!this.relationshipVisible(rel))return;let start=a.getWorldPosition(new THREE.Vector3()),end=b.getWorldPosition(new THREE.Vector3());const mutual=MUTUAL.has(type);if(DEPENDENCY_SOURCE.has(type))([start,end]=[end,start]);const mid=start.clone().lerp(end,.5);mid.x+=Math.min(14,start.distanceTo(end)*.12);const curve=new THREE.QuadraticBezierCurve3(start,mid,end),weight=this.relationshipWeight(rel),alpha=opacity??(highlight?Math.max(.38,.95*weight):Math.max(.08,.38*weight)),color=colorOverride??(type==='COMPETES_WITH'?0xb57b73:type==='INVESTS_IN'?0xc2a15d:highlight?0xe0c18d:0x87a5a4),group=new THREE.Group(),line=new THREE.Line(new THREE.BufferGeometry().setFromPoints(curve.getPoints(28)),new THREE.LineBasicMaterial({color,transparent:true,opacity:alpha,depthWrite:false}));group.add(line);if(!mutual){const at=.76,point=curve.getPoint(at),direction=curve.getTangent(at).normalize(),size=(highlight?1.05:.62)*(0.7+weight*.45),arrow=new THREE.Mesh(new THREE.ConeGeometry(size*.38,size,7),new THREE.MeshBasicMaterial({color,transparent:true,opacity:Math.min(1,alpha*1.35),depthWrite:false}));arrow.position.copy(point);arrow.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),direction);group.add(arrow)}group.userData={type,status:rel.status,activeFrom:rel.activeFrom,activeTo:rel.activeTo,weight};this.scene.add(group);this.lines.push(group)}
 select(id){this.selectedId=id;if(this.view==='gravity')return this.selectGravity(id);if(this.view==='models')return this.nodes.get(id)?.userData.entity.type==='Model'?this.selectModel(id):this.selectModelNode(id);this.clearLines();const rels=this.relationships.filter(r=>(r.source===id||r.target===id)&&(this.relationFilter==='ALL'||r.type===this.relationFilter)&&this.relationshipVisible(r));const adjacent=new Set([id]);rels.forEach(r=>{adjacent.add(r.source);adjacent.add(r.target);const a=this.nodes.get(r.source),b=this.nodes.get(r.target);if(a&&b)this.makeLine(a,b,r,true)});this.setActiveLabels(adjacent);this.nodes.forEach((n,nid)=>{n.material.opacity=adjacent.has(nid)?.98:.11;n.material.emissiveIntensity=nid===id?.75:adjacent.has(nid)?.22:.02;n.scale.setScalar(n.userData.baseScale*(nid===id?1.55:1))});this.focus(id)}
 selectGravity(id,maxHops=6,maxNodes=240){clearTimeout(this.gravityTimer);const eligible=this.relationships.filter(r=>(this.relationFilter==='ALL'||r.type===this.relationFilter)&&this.relationshipVisible(r)&&this.nodes.get(r.source)?.visible&&this.nodes.get(r.source)?.parent?.visible&&this.nodes.get(r.target)?.visible&&this.nodes.get(r.target)?.parent?.visible),hops=new Map([[id,0]]),queue=[id];while(queue.length&&hops.size<maxNodes){const current=queue.shift(),hop=hops.get(current);if(hop>=maxHops)continue;for(const r of eligible){const next=r.source===current?r.target:r.target===current?r.source:null;if(!next||hops.has(next))continue;hops.set(next,hop+1);queue.push(next);if(hops.size>=maxNodes)break}}const ids=[...hops.keys()],set=new Set(ids),edges=eligible.filter(r=>set.has(r.source)&&set.has(r.target));this.traceGraph(id,ids,edges,hops);this.frameNodes(ids);return {gravity:true,nodes:ids.length,edges:edges.length,hops:Math.max(0,...hops.values()),truncated:ids.length>=maxNodes}}
 buildModelBranch(root,direction,maxHops=6,maxNodes=90){const hops=new Map([[root,0]]),nodes=[root],queue=[root],edges=[],producerIds=direction==='downstream'?this.relationships.filter(r=>r.type==='DEVELOPS'&&r.target===root&&this.relationshipVisible(r)).map(r=>r.source):[];while(queue.length&&nodes.length<maxNodes){const current=queue.shift(),hop=hops.get(current);if(hop>=maxHops)continue;const pivots=current===root&&direction==='downstream'?[root,...producerIds]:[current];for(const pivot of pivots)for(const relationship of this.relationships){if((this.relationFilter!=='ALL'&&relationship.type!==this.relationFilter)||!this.relationshipVisible(relationship))continue;const next=directionalNeighbor(relationship,pivot,direction),entity=this.nodes.get(next)?.userData.entity;if(!next||!entity||next===root||(pivot!==root&&entity.type==='Model')||hops.has(next)||(this.activeGeography!=='all'&&entity.geography!==this.activeGeography)||!this.visibleLayers.has(entity.layer))continue;hops.set(next,hop+1);nodes.push(next);queue.push(next);edges.push(pivot===root?relationship:{...relationship,source:relationship.source===pivot?root:relationship.source,target:relationship.target===pivot?root:relationship.target});if(nodes.length>=maxNodes)break}}return {nodes,edges,hops,maxDepth:Math.max(0,...hops.values()),truncated:nodes.length>=maxNodes}}
 selectModel(id){clearTimeout(this.modelTimer);const creation=this.buildModelBranch(id,'upstream'),inference=this.buildModelBranch(id,'downstream'),creationSet=new Set(creation.nodes),inferenceNodes=inference.nodes.filter(node=>node===id||!creationSet.has(node)),ids=[...new Set([...creation.nodes,...inferenceNodes])],idSet=new Set(ids);this.activeModelRoot=id;this.modelTreeIds=idSet;this.modelTree={creation,inference:{...inference,nodes:inferenceNodes}};this.applyVisibility();const duration=this.reduced?1:850,positions=new Map([[id,new THREE.Vector3(0,0,0)]]),place=(branch,sign)=>{for(let hop=1;hop<=branch.maxDepth;hop++){const level=branch.nodes.filter(node=>node!==id&&branch.hops.get(node)===hop&&!positions.has(node)),span=Math.min(116,Math.max(16,(level.length-1)*8.5));level.forEach((node,index)=>positions.set(node,new THREE.Vector3(level.length===1?0:-span/2+span*index/(level.length-1),sign*hop*15,(index%3-1)*1.8)))}};place(creation,1);place(this.modelTree.inference,-1);this.nodes.forEach((node,nodeId)=>{if(!idSet.has(nodeId))return;this.ensureLabel(nodeId,nodeId===id?'model-label':'');node.scale.setScalar(node.userData.baseScale*(nodeId===id?1.85:1.18));node.userData.move={start:performance.now(),duration,from:node.position.clone(),to:positions.get(nodeId)||new THREE.Vector3()}});this.camera.up.set(0,1,0);this.cameraCommand('front');this.modelTimer=setTimeout(()=>this.drawModelTree(),this.reduced?5:900);return {model:true,creation:creation.nodes.length-1,inference:inferenceNodes.length-1,creationDepth:creation.maxDepth,inferenceDepth:inference.maxDepth,truncated:creation.truncated||inference.truncated}}
 drawModelTree(){if(this.view!=='models'||!this.modelTree)return;this.clearLines();const draw=(branch,color)=>branch.edges.forEach(edge=>{if(!this.modelTreeIds.has(edge.source)||!this.modelTreeIds.has(edge.target))return;const a=this.nodes.get(edge.source),b=this.nodes.get(edge.target);if(a?.visible&&b?.visible)this.makeLine(a,b,edge,true,.82,color)});draw(this.modelTree.creation,0xd8b474);draw(this.modelTree.inference,0x78b6aa);this.frameNodes([...this.modelTreeIds],550)}
 selectModelNode(id){if(!this.modelTreeIds?.has(id))return;this.nodes.forEach((node,nodeId)=>{const active=this.modelTreeIds.has(nodeId);node.material.opacity=active?(nodeId===id?1:.72):.03;node.material.emissiveIntensity=nodeId===id?.9:active?.18:.005;node.scale.setScalar(node.userData.baseScale*(nodeId===id?1.65:1.12))});this.focus(id,34);return {modelNode:true}}
 trace(ids){this.clearLines();const set=new Set(ids);this.setActiveLabels(set);this.nodes.forEach((n,id)=>{n.material.opacity=set.has(id)?.98:.065;n.material.emissiveIntensity=set.has(id)?.6:.01;n.scale.setScalar(n.userData.baseScale*(set.has(id)?1.25:1))});for(let i=0;i<ids.length-1;i++){const a=this.nodes.get(ids[i]),b=this.nodes.get(ids[i+1]);if(a&&b)this.makeLine(a,b,'DEPENDS_ON',true)}if(ids[0])this.focus(ids[0])}
 traceGraph(root,ids,edges,hops){this.clearLines();const set=new Set(ids),maxHop=Math.max(1,...hops.values());this.setActiveLabels(set);this.nodes.forEach((n,id)=>{const hop=hops.get(id),active=set.has(id);n.material.opacity=active?Math.max(.5,.98-(hop||0)*.075):.045;n.material.emissiveIntensity=id===root ? .9 : active?Math.max(.14,.62-(hop||0)*.08):.005;n.scale.setScalar(n.userData.baseScale*(id===root?1.6:active?Math.max(1.08,1.36-(hop||0)*.045):1))});edges.filter(edge=>this.relationshipVisible(edge)).forEach(edge=>{const a=this.nodes.get(edge.source),b=this.nodes.get(edge.target),hop=Math.max(hops.get(edge.source)||0,hops.get(edge.target)||0);if(a&&b)this.makeLine(a,b,edge,true,Math.max(.28,.96-hop/maxHop*.5))});this.focus(root,38)}
 resetStyles(){this.clearLines();this.setActiveLabels();this.nodes.forEach(n=>{n.material.opacity=n.userData.baseOpacity;n.material.emissiveIntensity=n.userData.baseEmissive;n.scale.setScalar(n.userData.baseScale)})}
 reset(){this.selectedId=null;if(this.view==='models'){this.activeModelRoot=null;this.modelTree=null;this.modelTreeIds=null;this.applyVisibility()}this.resetStyles();this.controls.autoRotate=this.view!=='models'&&this.activeGeography==='all'&&!this.reduced;this.relayout(true)}
 applyVisibility(){this.layerGroups.forEach((g,id)=>g.visible=this.visibleLayers.has(id));this.nodes.forEach(n=>{const e=n.userData.entity,geo=this.activeGeography==='all'||e.geography===this.activeGeography;n.visible=geo&&(this.view!=='models'?(true):this.modelTreeIds?this.modelTreeIds.has(e.id):this.modelOrder.has(e.id))});this.clearLines()}
 layoutPosition(entity,members){const layer=LAYERS.find(l=>l.id===entity.layer),layerIndex=LAYERS.indexOf(layer),index=members.indexOf(entity);if(this.view==='architecture'){const cols=Math.ceil(Math.sqrt(members.length));return new THREE.Vector3((index%cols-(cols-1)/2)*5.6,layer.y,(Math.floor(index/cols)-(Math.ceil(members.length/cols)-1)/2)*5.2)}
  const clusters=[...new Set(members.map(item=>item.cluster))],clusterIndex=clusters.indexOf(entity.cluster),clusterMembers=members.filter(item=>item.cluster===entity.cluster),within=clusterMembers.indexOf(entity),sector=Math.PI*2/clusters.length,spread=Math.min(.22,sector/Math.max(2,clusterMembers.length)),angle=clusterIndex*sector+(within-(clusterMembers.length-1)/2)*spread+layerIndex*.71,radius=24+layerIndex*3.05+(within%3)*1.5;return new THREE.Vector3(10+Math.cos(angle)*radius,layer.y+((within%3)-1)*1.15,Math.sin(angle)*radius)}
 layoutGravity(entity,order){const index=order.get(entity.id)||0,angle=index*2.3999632297,radius=index===0?0:5+Math.sqrt(index)*3.35,layerIndex=LAYERS.findIndex(layer=>layer.id===entity.layer);return new THREE.Vector3(Math.cos(angle)*radius,(layerIndex-(LAYERS.length-1)/2)*.32+(index%3-1)*.15,Math.sin(angle)*radius)}
 layoutModelGallery(entity,order){const index=order.get(entity.id)||0,columns=Math.max(7,Math.ceil(Math.sqrt(order.size*1.55))),row=Math.floor(index/columns),column=index%columns,rows=Math.ceil(order.size/columns);return new THREE.Vector3((column-(columns-1)/2)*10.5,(rows-1)/2*8.5-row*8.5,(index%3-1)*.65)}
 relayout(frame=false){const filtered=this.entities.filter(entity=>this.activeGeography==='all'||entity.geography===this.activeGeography),filteredIds=new Set(filtered.map(entity=>entity.id)),gravityOrder=new Map(this.gravityEntities.filter(entity=>filteredIds.has(entity.id)).map((entity,index)=>[entity.id,index])),byLayer=new Map(LAYERS.map(layer=>[layer.id,filtered.filter(entity=>entity.layer===layer.id)])),duration=this.reduced?1:850;
  const modelOrder=new Map(this.modelEntities.filter(entity=>filteredIds.has(entity.id)).map((entity,index)=>[entity.id,index]));this.nodes.forEach(node=>{const entity=node.userData.entity;if(!node.userData.eco)node.userData.eco=node.position.clone();if(!node.visible)return;const members=byLayer.get(entity.layer),target=this.view==='gravity'?this.layoutGravity(entity,gravityOrder):this.view==='models'?this.layoutModelGallery(entity,modelOrder):this.activeGeography==='all'&&this.view==='ecosystem'?node.userData.eco.clone():this.layoutPosition(entity,members),rank=gravityOrder.get(entity.id)||0,gravityBoost=this.view==='gravity'?1+Math.max(0,42-rank)/42*1.35:this.view==='models'?1.22:1;node.scale.setScalar(node.userData.baseScale*gravityBoost);node.userData.move={start:performance.now(),duration,from:node.position.clone(),to:target}});if(frame){if(this.view==='gravity'){this.cameraCommand('top');clearTimeout(this.gravityTimer);this.gravityTimer=setTimeout(()=>this.drawGravityWeb(),this.reduced?5:900)}else if(this.view==='models'){this.camera.up.set(0,1,0);this.cameraCommand('front')}else this.frameVisible(duration)}}
 frameVisible(duration=900){const visible=[...this.nodes.values()].filter(node=>node.visible&&node.parent?.visible),targets=visible.map(node=>node.userData.move?.to||node.position);if(!targets.length)return;const box=new THREE.Box3().setFromPoints(targets),center=box.getCenter(new THREE.Vector3()),size=box.getSize(new THREE.Vector3()),radius=Math.max(18,size.length()/2),distance=Math.min(245,Math.max(52,radius*1.75)),direction=new THREE.Vector3(1,.38,1.15).normalize();this.tween={start:performance.now(),duration:this.reduced?1:duration,from:this.camera.position.clone(),to:center.clone().add(direction.multiplyScalar(distance)),targetFrom:this.controls.target.clone(),targetTo:center}}
 frameNodes(ids,duration=650){const points=ids.map(id=>this.nodes.get(id)).filter(Boolean).map(node=>node.getWorldPosition(new THREE.Vector3()));if(!points.length)return;const box=new THREE.Box3().setFromPoints(points),center=box.getCenter(new THREE.Vector3()),size=box.getSize(new THREE.Vector3()),distance=Math.min(245,Math.max(46,size.length()*1.15)),direction=this.camera.position.clone().sub(this.controls.target).normalize();this.tween={start:performance.now(),duration:this.reduced?1:duration,from:this.camera.position.clone(),to:center.clone().add(direction.multiplyScalar(distance)),targetFrom:this.controls.target.clone(),targetTo:center}}
 drawGravityWeb(){if(this.view!=='gravity')return;this.clearLines();const visible=this.gravityEntities.filter(entity=>this.nodes.get(entity.id)?.visible&&this.nodes.get(entity.id)?.parent?.visible).slice(0,140),ids=new Set(visible.map(entity=>entity.id));this.relationships.filter(r=>(this.relationFilter==='ALL'||r.type===this.relationFilter)&&this.relationshipVisible(r)&&ids.has(r.source)&&ids.has(r.target)).forEach(r=>{const a=this.nodes.get(r.source),b=this.nodes.get(r.target);if(a&&b)this.makeLine(a,b,r,false)})}
 cameraCommand(action){this.controls.autoRotate=false;if(action==='fit'){this.camera.up.set(0,1,0);this.frameVisible();return}const visible=[...this.nodes.values()].filter(node=>node.visible&&node.parent?.visible),points=visible.map(node=>node.userData.move?.to||node.position);if(!points.length)return;const box=new THREE.Box3().setFromPoints(points),center=box.getCenter(new THREE.Vector3()),size=box.getSize(new THREE.Vector3()),distance=Math.min(245,Math.max(58,size.length()*1.05));if(action==='front'||action==='top'){this.camera.up.set(0,action==='front'?1:0,action==='front'?0:-1);const direction=action==='front'?new THREE.Vector3(0,.08,1):new THREE.Vector3(0,1,.001);this.tween={start:performance.now(),duration:this.reduced?1:700,from:this.camera.position.clone(),to:center.clone().add(direction.normalize().multiplyScalar(distance)),targetFrom:this.controls.target.clone(),targetTo:center};return}const factor=action==='zoom-in' ? .72 : 1.38,offset=this.camera.position.clone().sub(this.controls.target).multiplyScalar(factor);this.tween={start:performance.now(),duration:this.reduced?1:350,from:this.camera.position.clone(),to:this.controls.target.clone().add(offset),targetFrom:this.controls.target.clone(),targetTo:this.controls.target.clone()}}
 setLayers(ids){this.visibleLayers=new Set(ids);if(this.view==='models'){this.activeModelRoot=null;this.modelTree=null;this.modelTreeIds=null}this.applyVisibility();this.relayout(true)}
 setGeography(geography){this.activeGeography=geography;if(this.view==='models'){this.activeModelRoot=null;this.modelTree=null;this.modelTreeIds=null}this.applyVisibility();this.resetStyles();this.controls.autoRotate=this.view!=='models'&&geography==='all'&&!this.reduced;this.relayout(true)}
 setRelation(type){this.relationFilter=type;if(this.view==='gravity')this.drawGravityWeb();if(this.view==='models'&&this.activeModelRoot)this.selectModel(this.activeModelRoot)}
 setTime(year){this.timeYear=Number(year);this.clearLines();if(this.view==='models'&&this.activeModelRoot)this.selectModel(this.activeModelRoot);else if(this.selectedId)this.select(this.selectedId);else if(this.view==='gravity')this.drawGravityWeb()}
 setView(view){clearTimeout(this.gravityTimer);clearTimeout(this.modelTimer);this.view=view;this.activeModelRoot=null;this.modelTree=null;this.modelTreeIds=null;document.body.classList.toggle('models-view',view==='models');this.controls.autoRotate=false;this.architectureGuides.forEach(guide=>guide.visible=view!=='gravity'&&view!=='models');this.applyVisibility();this.resetStyles();this.relayout(true)}
}
