import { LAYERS,relationTypes,journeys,DATA_UPDATED,aliases } from './data.js';
import { GEOGRAPHIES } from './geography.js';
import { entityKind,ENTITY_KINDS } from './entity-kind.js';
import { TimelineView } from './timeline-view.js';
import { OfficeMapView } from './map-view.js';
const esc=s=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const DEPENDENCY_SOURCE=new Set(['RUNS_ON','TRAINS_ON','DEPENDS_ON','USES_MODEL_FROM']);
const MUTUAL=new Set(['PARTNERS_WITH','INTEGRATES_WITH','COMPETES_WITH']);
const directionalNeighbor=(relationship,current,direction)=>{if(MUTUAL.has(relationship.type))return relationship.source===current?relationship.target:relationship.target===current?relationship.source:null;const [consumer,provider]=DEPENDENCY_SOURCE.has(relationship.type)?[relationship.source,relationship.target]:[relationship.target,relationship.source];return direction==='upstream'?(consumer===current?provider:null):(provider===current?consumer:null)};
export function buildDirectionalTrace(relationships,root,direction,canVisit=()=>true,maxHops=6,maxNodes=180){const hops=new Map([[root,0]]),nodes=[root],edges=[],queue=[root];let truncated=false;while(queue.length){const current=queue.shift(),hop=hops.get(current);if(hop>=maxHops)continue;for(const relationship of relationships){const next=directionalNeighbor(relationship,current,direction);if(!next||!canVisit(next)||hops.has(next))continue;if(nodes.length>=maxNodes){truncated=true;continue}hops.set(next,hop+1);nodes.push(next);queue.push(next);edges.push(relationship)}}return {nodes,edges,hops,truncated,maxDepth:Math.max(0,...hops.values())}}
export class UI {
 constructor(entities,relationships,scene,select,officeLocations=[],submarineCableData={}){this.entities=entities;this.relationships=relationships;this.scene=scene;this.select=select;this.activeLayers=new Set(LAYERS.map(l=>l.id));this.activeGeography='all';this.timeline=new TimelineView(document.querySelector('#timelineView'),entities,relationships,select);this.officeMap=new OfficeMapView(document.querySelector('#officeMapView'),officeLocations,submarineCableData);document.querySelector('#searchInput').placeholder=`Search ${entities.length} entities`;document.querySelector('.updated').textContent=`DATA UPDATED ${new Date(`${DATA_UPDATED}T00:00:00`).toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'}).toUpperCase()}`;this.bind();this.bindFullscreen();this.bindModelPortfolio();this.renderScope()}
 bindModelPortfolio(){document.addEventListener('click',event=>{const target=event.target.closest('[data-entity]');if(target)queueMicrotask(()=>{this.renderEntityProfile(target.dataset.entity);this.renderModelPortfolio(target.dataset.entity)})})}
 renderModelPortfolio(id){const portfolio=this.scene.modelPortfolioByModel?.get(id),panel=document.querySelector('#detailPanel');if(!portfolio||panel.hidden||panel.querySelector('.model-portfolio'))return;const specialist=/image|sora|veo|lyria|embedding|robotics|guard|voice|imagine|movie|audio|ocr|code|coder|vision|vl|stable|flux|midjourney|runway|suno|music/i,section=document.createElement('section');section.className='model-portfolio';section.innerHTML=`<div class="portfolio-heading"><h3>Model portfolio over time</h3><small>${portfolio.items.length} nested models</small></div><div class="portfolio-rail">${portfolio.items.map((model,index)=>{const status=model.id===portfolio.root?'Current flagship':specialist.test(model.name)?'Current specialist':index<=3?'Previous generation':'Legacy';return `<button class="portfolio-model ${model.id===id?'selected':''}" data-entity="${model.id}"><i></i><span><strong>${esc(model.name)}</strong><small>${status}</small></span></button>`}).join('')}</div><p class="portfolio-note">Relative lifecycle status reflects this atlas edition. Exact release and retirement dates are used only when producers publish them consistently.</p>`;panel.querySelector('.lede')?.insertAdjacentElement('afterend',section)}
 renderEntityProfile(id){const entity=this.entities.find(item=>item.id===id),panel=document.querySelector('#detailPanel');if(!entity||panel.hidden||panel.querySelector('.entity-profile')||!entity.provides)return;const rows=[['Founded / launched',entity.founded],['Leadership',entity.leadership],['Headquarters',entity.headquarters],['Official website',entity.website?`<a href="${esc(entity.website)}" target="_blank" rel="noreferrer">Visit official site ↗</a>`:null]].filter(([,value])=>value),section=document.createElement('section');section.className='entity-profile';section.innerHTML=`<div class="profile-heading"><h3>Entity profile</h3><small>Verified basics</small></div><dl>${rows.map(([label,value])=>`<div><dt>${esc(label)}</dt><dd>${label==='Official website'?value:esc(value)}</dd></div>`).join('')}</dl><h4>What it provides</h4><p>${esc(entity.provides)}</p><h4>How it is used</h4><p>${esc(entity.howUsed)}</p>${entity.profileSources?.length?`<div class="profile-sources"><span>Sources</span>${entity.profileSources.map((source,index)=>`<a href="${esc(source)}" target="_blank" rel="noreferrer">${String(index+1).padStart(2,'0')} ↗</a>`).join('')}</div>`:''}`;panel.querySelector('.lede')?.insertAdjacentElement('afterend',section)}
 bind(){document.addEventListener('click',e=>{const button=e.target.closest('[data-action],[data-view],[data-entity],[data-journey],[data-camera]');if(!button)return;
   if(button.dataset.camera){this.scene.cameraCommand(button.dataset.camera);return}
   if(button.dataset.entity){this.select(button.dataset.entity);return}if(button.dataset.view){document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b===button));this.closeAll();const view=button.dataset.view;document.body.classList.toggle('timeline-mode',view==='timeline');document.body.classList.toggle('office-map-mode',view==='map');if(view==='map'){this.enter();this.timeline.hide();this.officeMap.show()}else{this.officeMap.hide();this.scene.setView(view);if(view==='timeline'){this.enter();this.timeline.show()}else this.timeline.hide()}const notice=document.querySelector('#traceNotice');if(view==='gravity'){notice.innerHTML='<strong>Gravity view</strong><span>Critical entities orbit nearest the center</span><small>Select any entity to reveal its connected supply-chain web across six hops.</small><button data-action="reset">Clear view ×</button>';notice.hidden=false}else if(view==='models'){notice.innerHTML=`<strong>Models view</strong><span>${this.scene.modelEntities.filter(model=>this.activeGeography==='all'||model.geography===this.activeGeography).length} leading model products across AI producers</span><small>Select a model to grow its creation tree upward and its deployment and inference ecosystem downward.</small><button data-action="reset">Reset models ×</button>`;notice.hidden=false}else notice.hidden=true;return}if(button.dataset.journey){this.startJourney(journeys.find(j=>j.id===button.dataset.journey));return}
   const a=button.dataset.action;if(a==='explore')this.enter();if(a==='toggle-dock')this.toggleDock();if(a==='reset'){this.closeAll();this.scene.reset()}if(a==='layers')this.showFilters('layers');if(a==='relations')this.showFilters('relations');if(a==='time')this.showTime();if(a==='geography')this.showFilters('geography');if(a==='journeys')this.showJourneys();if(a==='fullscreen')this.toggleFullscreen();if(a==='methodology')this.showMethod();if(a==='close')button.closest('aside,.journey-player')?.setAttribute('hidden','');if(a==='upstream'||a==='downstream')this.traceDirection(button.dataset.id,a);if(a==='stack')this.traceStack(button.dataset.id);if(a==='journey-next')this.advanceJourney(1);if(a==='journey-prev')this.advanceJourney(-1);if(a==='stop-journey')this.stopJourney();
  });
  const input=document.querySelector('#searchInput');input.addEventListener('input',()=>this.search(input.value));input.addEventListener('keydown',e=>{if(e.key==='Escape'){input.value='';this.search('')}});document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();input.focus()}if(e.key==='Escape')this.closeAll();if(e.target.matches('input,textarea'))return;const cameraKeys={'0':'fit','1':'front','2':'top','+':'zoom-in','=':'zoom-in','-':'zoom-out'};if(cameraKeys[e.key])this.scene.cameraCommand(cameraKeys[e.key])});
 }
 toggleDock(){const dock=document.querySelector('.control-dock'),button=dock.querySelector('.dock-toggle'),collapsed=dock.classList.toggle('is-collapsed');button.textContent=collapsed?'+':'−';button.setAttribute('aria-expanded',String(!collapsed));button.setAttribute('aria-label',collapsed?'Restore explore controls':'Minimize explore controls');button.title=collapsed?'Restore controls':'Minimize controls';if(collapsed)document.querySelector('#searchResults').hidden=true}
 bindFullscreen(){const button=document.querySelector('[data-action="fullscreen"]');if(!button)return;if(!document.documentElement.requestFullscreen){button.disabled=true;button.title='Fullscreen is unavailable in this browser';button.setAttribute('aria-label',button.title);return}document.addEventListener('fullscreenchange',()=>{const active=Boolean(document.fullscreenElement),label=active?'Exit fullscreen':'Enter fullscreen';button.dataset.fullscreen=String(active);button.title=label;button.setAttribute('aria-label',label);button.setAttribute('aria-pressed',String(active))})}
 async toggleFullscreen(){try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen()}catch(error){console.warn('Unable to change fullscreen mode:',error)}}
 enter(){document.body.classList.add('entered');document.querySelector('.intro').setAttribute('aria-hidden','true');this.scene.controls.autoRotate=false}
 closeAll(){['detailPanel','filterPanel','journeyPanel','methodPanel','journeyPlayer','traceNotice'].forEach(id=>document.querySelector('#'+id).hidden=true);document.querySelector('#searchResults').hidden=true}
 search(q){const box=document.querySelector('#searchResults'),s=q.trim().toLowerCase();if(!s){box.hidden=true;return}const hits=this.entities.filter(e=>(this.activeGeography==='all'||e.geography===this.activeGeography)&&[e.name,e.type,e.layer,e.country,e.geography,...e.categories,...e.products].join(' ').toLowerCase().includes(s)).sort((a,b)=>(b.name.toLowerCase().startsWith(s)?1:0)-(a.name.toLowerCase().startsWith(s)?1:0)||b.importanceLevel-a.importanceLevel).slice(0,12);box.innerHTML=hits.length?hits.map(e=>{const kind=entityKind(e);return `<button data-entity="${e.id}"><i class="kind-mark ${kind}" style="--c:${LAYERS.find(l=>l.id===e.layer).color}"></i><span><strong>${esc(e.name)}</strong><small>${esc(ENTITY_KINDS[kind].short)} · ${esc(e.geography)} · ${esc(e.categories.at(-1))}</small></span><b>↗</b></button>`}).join(''):'<p>No entities found in this geography</p>';box.hidden=false}
 showEntity(id){const e=this.entities.find(x=>x.id===id);if(!e)return;this.enter();this.closeAll();const selection=this.scene.select(id),rels=this.relationships.filter(r=>r.source===id||r.target===id),up=rels.filter(r=>r.target===id),down=rels.filter(r=>r.source===id),related=[...new Set(rels.map(r=>r.source===id?r.target:r.source))].map(x=>this.entities.find(e=>e.id===(aliases[x]||x))).filter(Boolean).slice(0,8),kind=entityKind(e),kindMeta=ENTITY_KINDS[kind];const layer=LAYERS.find(l=>l.id===e.layer);const p=document.querySelector('#detailPanel');p.innerHTML=`<div class="panel-head"><span style="--c:${layer.color}">${layer.symbol} ${esc(layer.short)}</span><button data-action="close" aria-label="Close">×</button></div><p class="entity-type"><i class="kind-glyph ${kind}">${kindMeta.symbol}</i> ${esc(kindMeta.label)} · ${esc(e.type)} · ${esc(e.country)}</p><h2>${esc(e.name)}</h2><p class="lede">${esc(e.description)}</p><div class="entity-stats"><div><small>UPSTREAM</small><strong>${up.length}</strong></div><div><small>DOWNSTREAM</small><strong>${down.length}</strong></div><div><small>RELATIONS</small><strong>${rels.length}</strong></div></div><div class="trace-actions"><button data-action="upstream" data-id="${id}">← Trace upstream</button><button data-action="downstream" data-id="${id}">Trace downstream →</button></div><button class="stack-button" data-action="stack" data-id="${id}">✦ Trace a representative stack</button><section><h3>Ecosystem role</h3><p>${esc(e.ecosystemRole)}</p></section><section><h3>Significant products / technologies</h3><div class="chips">${e.products.map(x=>`<span>${esc(x)}</span>`).join('')}</div></section><section><h3>Why it matters</h3><p>${esc(e.whyItMatters)}</p></section><section><h3>Immediate network</h3><div class="related">${related.map(x=>`<button data-entity="${x.id}">${esc(x.name)} <span>↗</span></button>`).join('')||'<p>No direct relationships in this edition.</p>'}</div></section><section><h3>Relationship evidence</h3>${rels.slice(0,8).map(r=>{const other=this.entities.find(x=>x.id===(aliases[r.source===id?r.target:r.source]|| (r.source===id?r.target:r.source)));return `<div class="relation-row"><span>${esc(r.type.replaceAll('_',' '))}</span><strong>${esc(other?.name||'Cross-layer capability')}</strong><small class="status ${r.status}">${esc(r.status)}</small><p>${esc(r.explanation)}</p></div>`}).join('')}</section>`;p.hidden=false;if(selection?.model){const notice=document.querySelector('#traceNotice');notice.innerHTML=`<strong>${esc(e.name)}</strong><span><b class="creation-key">${selection.creation}</b> creation entities above · <b class="inference-key">${selection.inference}</b> deployment/inference entities below</span><small>Gold branches trace model creation; green roots trace known deployment and downstream use across up to six hops.${selection.truncated?' Large branches are capped for legibility.':''}</small><button data-action="reset">Back to models ×</button>`;notice.hidden=false}}
 showFilters(tab){
  this.closeAll();const p=document.querySelector('#filterPanel');p.hidden=false;
  const layerBody=LAYERS.map(l=>`<label><input type="checkbox" value="${l.id}" ${this.activeLayers.has(l.id)?'checked':''}><i style="--c:${l.color}">${l.symbol}</i><span>${esc(l.name)}</span></label>`).join('');
  const relationBody=`<label><input type="radio" name="relation" value="ALL" ${this.scene.relationFilter==='ALL'?'checked':''}><span>All relationship types</span></label>${relationTypes.map(r=>`<label><input type="radio" name="relation" value="${r}" ${this.scene.relationFilter===r?'checked':''}><span>${esc(r.replaceAll('_',' '))}</span></label>`).join('')}`;
  const geographyBody=GEOGRAPHIES.map(g=>`<label class="geo-option"><input type="radio" name="geography" value="${g.id}" ${this.activeGeography===g.id?'checked':''}><i>${g.short}</i><span><strong>${esc(g.name)}</strong><small>${this.entities.filter(e=>g.id==='all'||e.geography===g.id).length} entities · ${esc(g.description)}</small></span></label>`).join('');
  const body=tab==='layers'?layerBody:tab==='relations'?relationBody:geographyBody;
  p.innerHTML=`<div class="panel-head"><strong>Universe controls</strong><button data-action="close">×</button></div><div class="tabbar"><button class="${tab==='layers'?'active':''}" data-filtertab="layers">Layers</button><button class="${tab==='relations'?'active':''}" data-filtertab="relations">Relationships</button><button class="${tab==='geography'?'active':''}" data-filtertab="geography">Geography</button></div><div class="filter-list">${body}</div>`;
  p.querySelectorAll('[data-filtertab]').forEach(b=>b.onclick=()=>this.showFilters(b.dataset.filtertab));p.querySelectorAll('input').forEach(input=>input.onchange=()=>{if(input.type==='checkbox'){input.checked?this.activeLayers.add(input.value):this.activeLayers.delete(input.value);this.scene.setLayers(this.activeLayers)}else if(input.name==='geography'){this.activeGeography=input.value;this.scene.setGeography(input.value);const geo=GEOGRAPHIES.find(g=>g.id===input.value);document.querySelector('#geoLabel').textContent=geo.short;p.hidden=true}else{this.scene.setRelation(input.value);document.querySelector('[data-action="relations"] b').textContent=input.value==='ALL'?'ALL':'1'}this.renderScope()})
 }
 showTime(){this.closeAll();const p=document.querySelector('#filterPanel'),dated=this.relationships.filter(r=>r.activeFrom||r.activeTo).length;p.hidden=false;p.innerHTML=`<div class="panel-head"><strong>Relationship time</strong><button data-action="close">×</button></div><div class="time-control"><div class="time-readout"><strong id="timeReadout">${this.scene.timeYear}</strong><span>As-of snapshot</span></div><input id="timeRange" type="range" min="2000" max="2026" step="1" value="${this.scene.timeYear}" aria-label="Relationship snapshot year"><div class="time-ticks"><span>2000</span><span>2010</span><span>2020</span><span>2026</span></div><p>Edges with verified start or end years enter and leave the map as you scrub. Undated relationships remain visible at lower intensity so missing research is not mistaken for historical absence.</p><div class="time-key"><i></i><span>Dated relationship</span><i class="uncertain"></i><span>Date not yet audited</span></div><p>${dated} of ${this.relationships.length} relationships currently have explicit temporal metadata.</p></div>`;const range=p.querySelector('#timeRange'),readout=p.querySelector('#timeReadout');range.oninput=()=>{readout.textContent=range.value;document.querySelector('#timeLabel').textContent=range.value;this.scene.setTime(range.value)} }
 showJourneys(){this.closeAll();const p=document.querySelector('#journeyPanel');p.hidden=false;p.innerHTML=`<div class="panel-head"><div><p class="eyebrow">Curated pathways</p><h2>Guided journeys</h2></div><button data-action="close">×</button></div><p>Follow representative routes through the ecosystem. Each stop explains a handoff, dependency or control point.</p><div class="journey-list">${journeys.map((j,i)=>`<button data-journey="${j.id}"><span>${String(i+1).padStart(2,'0')}</span><div><strong>${esc(j.title)}</strong><small>${esc(j.kicker)}</small></div><b>→</b></button>`).join('')}</div>`}
 startJourney(j){if(!j)return;this.closeAll();this.currentJourney=j;this.journeyStep=0;this.renderJourneyStep()}
 renderJourneyStep(){const j=this.currentJourney,id=j.nodes[this.journeyStep],e=this.entities.find(x=>x.id===id),next=this.entities.find(x=>x.id===j.nodes[this.journeyStep+1]);this.scene.trace(j.nodes.slice(0,this.journeyStep+1));this.scene.focus(id,27);const p=document.querySelector('#journeyPlayer');p.hidden=false;p.innerHTML=`<div class="journey-progress"><i style="width:${(this.journeyStep+1)/j.nodes.length*100}%"></i></div><div class="journey-meta"><span>${String(this.journeyStep+1).padStart(2,'0')} / ${String(j.nodes.length).padStart(2,'0')}</span><button data-action="stop-journey">Exit journey ×</button></div><p class="eyebrow">${esc(j.title)}</p><h2>${esc(e.name)}</h2><p>${this.journeyStep===0?esc(j.summary):next?`${esc(e.name)} connects upward to ${esc(next.name)} in this representative route. ${esc(e.ecosystemRole)}`:`${esc(e.whyItMatters)}`}</p><div><button data-action="journey-prev" ${this.journeyStep===0?'disabled':''}>←</button><button data-action="journey-next">${this.journeyStep===j.nodes.length-1?'Finish':'Next stop →'}</button></div>`}
 advanceJourney(n){if(n>0&&this.journeyStep===this.currentJourney.nodes.length-1){this.stopJourney();return}this.journeyStep=Math.max(0,Math.min(this.currentJourney.nodes.length-1,this.journeyStep+n));this.renderJourneyStep()}
 stopJourney(){document.querySelector('#journeyPlayer').hidden=true;this.scene.reset()}
 traceDirection(id,dir){const eligible=this.relationships.filter(r=>(this.scene.relationFilter==='ALL'||r.type===this.scene.relationFilter)&&this.scene.relationshipVisible(r)).map(r=>({...r,source:aliases[r.source]||r.source,target:aliases[r.target]||r.target})),canVisit=next=>{const node=this.scene.nodes.get(next);return Boolean(node?.visible&&node.parent?.visible)},trace=buildDirectionalTrace(eligible,id,dir,canVisit);this.scene.traceGraph(id,trace.nodes,trace.edges,trace.hops);const byHop=[];for(let hop=1;hop<=trace.maxDepth;hop++)byHop.push(`${hop}: ${trace.nodes.filter(node=>trace.hops.get(node)===hop).length}`);const notice=document.querySelector('#traceNotice');notice.innerHTML=`<strong>${dir==='upstream'?'Upstream dependencies':'Downstream reach'}</strong><span>${trace.nodes.length-1} entities across ${trace.maxDepth} hop${trace.maxDepth===1?'':'s'} · ${this.scene.timeYear} snapshot</span><small>${byHop.length?`Entities by hop · ${byHop.join(' · ')}`:'No connected entities in the current filters'}${trace.truncated?' · Limited to 180 entities':''}</small><button data-action="reset">Clear trace ×</button>`;notice.hidden=false;document.querySelector('#detailPanel').hidden=true}
 traceStack(id){const {representativePaths}=window.ecosystemData;let path=representativePaths[id];if(!path){const e=this.entities.find(x=>x.id===id),defaults={models:[id,'vllm','aws','nvidia','sk-hynix','tsmc','asml'],applications:[id,'openai','vllm','azure','nvidia','sk-hynix','tsmc','asml'],agents:[id,'anthropic','vllm','aws','nvidia','sk-hynix','tsmc','asml'],robotics:[id,'pytorch','cuda','nvidia','sk-hynix','tsmc','asml']};path=defaults[e.layer]||[id,...this.relationships.filter(r=>r.target===id).slice(0,5).map(r=>r.source)]}path=path.filter(x=>this.scene.nodes.has(x));this.scene.trace(path);const notice=document.querySelector('#traceNotice');notice.innerHTML=`<strong>Representative dependency path</strong><span>${path.map(x=>this.entities.find(e=>e.id===x)?.name).join(' → ')}</span><small>This path is illustrative, not the only supply chain.</small><button data-action="reset">Clear trace ×</button>`;notice.hidden=false;document.querySelector('#detailPanel').hidden=true}
 showMethod(){this.closeAll();const p=document.querySelector('#methodPanel');p.hidden=false;p.innerHTML=`<div class="panel-head"><div><p class="eyebrow">About this atlas</p><h2>Methodology</h2></div><button data-action="close">×</button></div><p class="method-lede">A navigational model of a rapidly changing industry—not an exhaustive or authoritative supply-chain database.</p><section><h3>How to read the system</h3><p>Entities are arranged from physical inputs at the base to end markets at the edge. A company may appear through several technologies and relationships rather than being forced into one category.</p></section><section><h3>Relationship confidence</h3><ul><li><b>Confirmed</b> — disclosed by the organizations or broadly documented.</li><li><b>Reported</b> — described by credible public reporting.</li><li><b>Inferred</b> — a reasonable industry inference, explicitly marked.</li><li><b>Representative</b> — illustrates a common architecture, not a unique contract.</li></ul></section><section><h3>Scope & maintenance</h3><p>This edition prioritizes structural importance over completeness. Relationships change quickly; absence does not imply no relationship. Representative paths simplify a multi-supplier reality to make the stack legible.</p></section><div class="data-stamp"><span>DATA EDITION</span><strong>${DATA_UPDATED}</strong><small>${this.entities.length} entities · ${this.relationships.length} relationships</small></div>`}
 renderScope(){const visible=this.entities.filter(e=>this.activeLayers.has(e.layer)&&(this.activeGeography==='all'||e.geography===this.activeGeography));const geo=GEOGRAPHIES.find(g=>g.id===this.activeGeography);document.querySelector('#scopeCount').textContent=`${visible.length} ENTITIES · ${this.activeLayers.size} LAYERS · ${geo.short}`;document.querySelector('#layerCount').textContent=`${this.activeLayers.size}/${LAYERS.length}`;this.timeline.setScope(this.activeLayers,this.activeGeography)}
}
